version: '3.5'

services:

  postgres:
    image: postgres:10.1-alpine
    container_name: postgres-students
    environment:
      POSTGRES_USER: studentmgt-user
      POSTGRES_PASSWORD: studentmgt-password
      POSTGRES_DB: studentsmgt
    ports:
      - 5432:5432
    volumes:
      - ./db_init:/db_init
      - studentsmgt_db:/var/lib/postgresql/data

  backend-students:
    container_name: backend-students
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_NAME: studentsmgt
      DB_USER: studentmgt-user
      DB_PASS: studentmgt-password
    # restart: always
    depends_on:
      - postgres
    links:
      - postgres


volumes:
  studentsmgt_db:
  student-management:

# networks:
#   esnet:
